security:
    role_hierarchy:
        ROLE_SHOP_ADMIN_STORES_RO:
            - ROLE_SHOP_ADMIN_STORES_LIST
            - ROLE_SHOP_ADMIN_STORES_READ
        ROLE_SHOP_ADMIN_STORES_RW:
            - ROLE_SHOP_ADMIN_STORES_RO
            - ROLE_SHOP_ADMIN_STORES_CREATE
            - ROLE_SHOP_ADMIN_STORES_UPDATE
            - ROLE_SHOP_ADMIN_STORES_DELETE

        ROLE_SHOP_ADMIN_ORDERS_RO:
            - ROLE_SHOP_ADMIN_ORDERS_LIST
            - ROLE_SHOP_ADMIN_ORDERS_DETAILS
        ROLE_SHOP_ADMIN_ORDERS_RW:
            - ROLE_SHOP_ADMIN_ORDERS_RO
            - ROLE_SHOP_ADMIN_ORDERS_CREATE
            - ROLE_SHOP_ADMIN_ORDERS_UPDATE
            - ROLE_SHOP_ADMIN_ORDERS_DELETE

        ROLE_SHOP_ADMIN_CUSTOMERS_RO:
            - ROLE_SHOP_ADMIN_CUSTOMERS_LIST
            - ROLE_SHOP_ADMIN_CUSTOMERS_DETAILS
        ROLE_SHOP_ADMIN_CUSTOMERS_RW:
            - ROLE_SHOP_ADMIN_CUSTOMERS_RO
            - ROLE_SHOP_ADMIN_CUSTOMERS_CREATE
            - ROLE_SHOP_ADMIN_CUSTOMERS_UPDATE
            - ROLE_SHOP_ADMIN_CUSTOMERS_DELETE

        ROLE_SHOP_ADMIN_RO:
            - ROLE_SHOP_ADMIN_STORES_RO
            - ROLE_SHOP_ADMIN_ORDERS_RO
            - ROLE_SHOP_ADMIN_CUSTOMERS_RO

        ROLE_SHOP_ADMIN_RW:
            - ROLE_SHOP_ADMIN_STORES_RW
            - ROLE_SHOP_ADMIN_ORDERS_RW
            - ROLE_SHOP_ADMIN_CUSTOMERS_RW


