services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $storeRouteParamName: '%sfs_shop.store.route_param_name%'

    Softspring\ShopBundle\EventListener\StoreDoctrineFilterListener:
        tags: ['kernel.event_subscriber']

    Softspring\ShopBundle\EventListener\StoreRequestListener:
        tags: ['kernel.event_subscriber']