services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_shop.entity_manager'

    Softspring\ShopBundle\Controller\:
        resource: '../../../Controller/*'
        public: true

    Softspring\ShopBundle\Entity\EntityListener\StoreOrderTransitionsListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'Softspring\ShopBundle\Model\Order', lazy: true }
            - { name: 'doctrine.orm.entity_listener', event: 'prePersist', entity: 'Softspring\ShopBundle\Model\Order', lazy: true }

    Softspring\ShopBundle\EventListener\TransitionStoreListener:
        tags: ['doctrine.event_subscriber']

    Softspring\ShopBundle\Form\:
        resource: '../../../Form/*'

    Softspring\ShopBundle\Manager\:
        resource: '../../../Manager/*'

    Softspring\ShopBundle\Request\ParamConverter\:
        resource: '../../../Request/ParamConverter/*'
        tags: ['request.param_converter']

    Softspring\ShopBundle\Twig\Extension\:
        resource: '../../../Twig/Extension/*'
        tags: ['twig.extension']
