sfs_shop_admin_orders_list:
    controller: sfs_shop.admin.order.controller::list
    path: /

sfs_shop_admin_orders_create:
    controller: sfs_shop.admin.order.controller::create
    path: /create

sfs_shop_admin_orders_update:
    controller: sfs_shop.admin.order.controller::update
    path: /{entity}/update

sfs_shop_admin_orders_delete:
    controller: sfs_shop.admin.order.controller::delete
    path: /{entity}/delete

sfs_shop_admin_orders_read:
    controller: sfs_shop.admin.order.controller::read
    path: /{entity}

sfs_shop_admin_orders_transition:
    controller: Softspring\ShopBundle\Controller\Admin\OrderController::transition
    path: /{order}/{transition}
