sfs_shop_admin_stores_list:
    controller: sfs_shop.admin.store.controller::list
    path: /

sfs_shop_admin_stores_create:
    controller: sfs_shop.admin.store.controller::create
    path: /create

sfs_shop_admin_stores_update:
    controller: sfs_shop.admin.store.controller::update
    path: /{store}/update

sfs_shop_admin_stores_delete:
    controller: sfs_shop.admin.store.controller::delete
    path: /{store}/delete

sfs_shop_admin_stores_read:
    controller: sfs_shop.admin.store.controller::read
    path: /{store}
