sfs_shop_admin_customers_list:
    controller: sfs_shop.admin.customer.controller::list
    path: /

sfs_shop_admin_customers_create:
    controller: sfs_shop.admin.customer.controller::create
    path: /create

sfs_shop_admin_customers_update:
    controller: sfs_shop.admin.customer.controller::update
    path: /{customer}/update

sfs_shop_admin_customers_delete:
    controller: sfs_shop.admin.customer.controller::delete
    path: /{customer}/delete

sfs_shop_admin_customers_read:
    controller: sfs_shop.admin.customer.controller::read
    path: /{customer}
