sfs_shop_cart_view:
    controller: Softspring\ShopBundle\Controller\CartController::view
    path: /
    methods: ['GET']

sfs_shop_cart_update:
    controller: Softspring\ShopBundle\Controller\CartController::update
    path: /
    methods: ['POST']

sfs_shop_cart_add:
    controller: Softspring\ShopBundle\Controller\CartController::addItem
    path: /add
    requirements:
        item: ".+"

sfs_shop_cart_remove:
    controller: Softspring\ShopBundle\Controller\CartController::removeItem
    path: /remove
    requirements:
        item: ".+"

sfs_shop_cart_finished:
    controller: Softspring\ShopBundle\Controller\CartController::finished
    path: /{order}/finished

sfs_shop_cart_transition:
    controller: Softspring\ShopBundle\Controller\CartController::transition
    path: /{transition}