sfs_shop_cart_view:
    controller: Softspring\ShopBundle\Controller\CartController::view
    path: /
    methods: ['GET']

sfs_shop_cart_update:
    controller: Softspring\ShopBundle\Controller\CartController::update
    path: /
    methods: ['POST']

sfs_shop_cart_add:
    controller: Softspring\ShopBundle\Controller\CartController::addItem
    path: /{item}/add

sfs_shop_cart_remove:
    controller: Softspring\ShopBundle\Controller\CartController::removeItem
    path: /{item}/remove

sfs_shop_cart_finished:
    controller: Softspring\ShopBundle\Controller\CartController::finished
    path: /{order}/finished

sfs_shop_cart_transition:
    controller: Softspring\ShopBundle\Controller\CartController::transition
    path: /{transition}