sfs_shop_cart_view:
    controller: Softspring\ShopBundle\Controller\CartController::view
    path: /

sfs_shop_cart_reset:
    controller: Softspring\ShopBundle\Controller\CartController::reset
    path: /reset

sfs_shop_cart_add:
    controller: Softspring\ShopBundle\Controller\CartController::addItem
    path: /{item}/add

sfs_shop_cart_remove:
    controller: Softspring\ShopBundle\Controller\CartController::removeItem
    path: /{item}/remove


